# LAB 01 - NumPy Library 1

## 01 Numpy 시작하기

#### 라이브러리 참조하기

In [1]:
import numpy as np

### 배열 생성하기 : 리스트를 통한 1차원 배열 만들기


In [4]:
#리스트를 파라미터로 전달하여 ndarray 객체 생성
arr = np.array([1,3,5,7,9])
print(type(arr))
arr

<class 'numpy.ndarray'>


array([1, 3, 5, 7, 9])

### 배열의 크기 
len() 함수를 사용하면 배열의 크기를 확인할 수 있다

In [7]:
arr = np.array([10,30,50,70,90])
size=len(arr)
print("배열의 원소는 %d 개 입니다" %size)

배열의 원소는 5 개 입니다


### 배열의 인덱싱과 슬라이싱
기본 특성은 리스트와 동일하기 때문에 리스트처럼 인덱싱과 슬라이싱이 가능하다

In [11]:
mydata = np.array([5,10,15,20,25])

#인덱싱을 사용한 원소 접근

print(mydata[0])
print(mydata[3])
print(mydata[4])


#슬라이싱을 사용한 구간 추출도 가능
print(mydata[1:4])
print(mydata[-4:-1])

5
20
25
[10 15 20]
[10 15 20]


### 반복문을 통한 활용
리스트와 동일하게 사용할 수 있다

In [13]:
mydata = np.array([100,110,120,130,140])

for i,v in enumerate(mydata):
  print("%d 번쨰 원소 >> %d"%(i,v))
  

0 번쨰 원소 >> 100
1 번쨰 원소 >> 110
2 번쨰 원소 >> 120
3 번쨰 원소 >> 130
4 번쨰 원소 >> 140


### ndarray 의 특성
- list 의 경우 다른 데이터 타입의 원소를 허용하지만, ndarray 의 경우 가장 포괄적인 데이터 타입으로 변환한다
- 정수형은 "100." 형태로, boolean 은 False 는 0, True 는 1로 반환된다.


In [14]:
mylist =[100,3.14,True]
print("리스트에는 다양한 형태의 데이터가 들어올 수 있어요",mylist)

myarray =np.array(mylist)
print("배열은 다양한 형태의 데이터가 들어올 수 없어요",myarray)

리스트에는 다양한 형태의 데이터가 들어올 수 있어요 [100, 3.14, True]
배열은 다양한 형태의 데이터가 들어올 수 없어요 [100.     3.14   1.  ]
