# LAB 01 - NumPy Library 1

## 02 ndarray 의 주요 기능

### 라이브러리 참조하기

In [2]:
#numpy 라이브러리를 np 라는 이름으로 사용하도록 import
import numpy as np

### 타입 지정
- dtype 파라미터를 사용한 강제 타입 지정.
- ndarray 를 생성할 때, dtype 이라는 파라미터로 특정 타입을 강제로 지정할 수 있따
- 만약 실수형 값을 정수로 변환하게 되면 소수점 아래는 모두 버린다


In [9]:
mylist1 = [100.12,3.14,1.5]
myarr1=np.array(mylist1,dtype="int")   #float 형태의 데이터들을 강제로 int 로 바꿔주니 소수점을 다 버림 
myarr1

array([100,   3,   1])

### 문자열이 포함된 경우의 형변환
- 모든 프로그래밍 언어에서 문자열은 표현 범위가 가장 넓은 데이터 타입이다
- 만약 배열로 변환하려는 리스트에 문자열이 하나라도 포함되어 있을 경우 모든 원소가 문자열이 된다
  

In [11]:
mylist2 = [1.2,3,True,'4']
myarr2 = np.array(mylist2)
myarr2

array(['1.2', '3', 'True', '4'], dtype='<U32')

### 리스트 타입으로 역변환
- ndarray 와 list 는 서로 호환이 가능하다
- 만약 어떤 함수에서 파라미터로 리스트를 전송해야하면, 그 떄 ndarray 를 쓸 수 도 있다

In [14]:
mylist3 =[10,20,30,40,50]
myarr3 = np.array(mylist3)   #리스트를 np.array 로 감싸주면 ndarray 타입이 된다
print(type(myarr3),myarr3)   


mylist3_1 = list(myarr3) #ndarray 타입을 list() 함수로 감사주면 리스트 타입이 된다
print(type(mylist3_1),mylist3_1)

<class 'numpy.ndarray'> [10 20 30 40 50]
<class 'list'> [np.int64(10), np.int64(20), np.int64(30), np.int64(40), np.int64(50)]


### 연산자를 사용한 ndarray 연산
- 리스트에서는 리스트를 더하면 [a,a,a,b,b,b] 이렇게 뒤에 이어지는 형태였지만 ndarray 에서는 원소의 위치에 대응되어 더해진다

In [17]:
arr1 = np.array([10,15,20,25,30])
arr2 = np.array([2,3,4,5,6])

print(arr1)
print(arr2)

[10 15 20 25 30]
[2 3 4 5 6]


In [25]:
#  더하기
a=arr1+arr2
print("arr+arr2 > ", a)

# 뺴기

b=arr1-arr2
print("arr-arr2 > ",b)

# 곱하기
c=arr1*arr2
print("arr*arr2 > ",c)


# 나누기
d=arr1/arr2
print("arr/arr2 > ",d)

arr+arr2 >  [12 18 24 30 36]
arr-arr2 >  [ 8 12 16 20 24]
arr*arr2 >  [ 20  45  80 125 180]
arr/arr2 >  [5. 5. 5. 5. 5.]


### NumPy 의 함수를 사용한 연산
연산자를 사용한 경우와 동일한 결과를 얻을 수 있는 내장 함수가 존재한다

In [26]:
arr1 = np.array([10,15,20,25,30])
arr2 = np.array([2,3,4,5,6])

print(arr1)
print(arr2)

[10 15 20 25 30]
[2 3 4 5 6]


In [30]:
#  더하기
a=np.add(arr1,arr2)
print("arr+arr2 > ", a)

# 뺴기

b=np.subtract(arr1,arr2)
print("arr-arr2 > ",b)

# 곱하기
c=np.multiply(arr1,arr2)
print("arr*arr2 > ",c)


# 나누기
d=np.divide(arr1,arr2)
print("arr/arr2 > ",d)

arr+arr2 >  [12 18 24 30 36]
arr-arr2 >  [ 8 12 16 20 24]
arr*arr2 >  [ 20  45  80 125 180]
arr/arr2 >  [5. 5. 5. 5. 5.]


### 조건에 맞는 위치의 원소 추출
특정 배열에서 True 에 해당하는 값만 추출할 수도 있다

In [36]:
grade = np.array([82,77,91,88])
print("점수 리스트는" ,grade)


#추출하고자 하는 원본과 같은 사이트의 배열을 생성해서 True 와 False 로 구분해준다
bool_array = np.array([True,False,True,False])
print("구별 리스트는" , bool_array)


#True 에 해당하는 원소만 추출
result1 = grade[bool_array]
print("점수 리스트에서 True 에 해당한 원소들은",result1)


점수 리스트는 [82 77 91 88]
구별 리스트는 [ True False  True False]
점수 리스트에서 True 에 해당한 원소들은 [82 91]


### 조건식에 따른 원소 추출
위의 예제처럼 True 에 해당하는 항목만 추출할 수 있었던 것처럼, 특정 조건에 해당하는 원소들만 추출하도록 조건을 세부화할 수 있다

In [41]:
# 80점 이상인 원소만 추출해보기

mypoint = np.array([82,77,91,88])
ge80 = mypoint[mypoint>=80]

print("80점이 넘는 원소들의 모음",ge80)



#2개 이상의 조건을 and 로 묶어줄 떄 쓸 수 있는 np.logical_and 함수

ge90and90 = mypoint[np.logical_and(mypoint>=80,mypoint<=90)]
print("80점 이상이면서 90점 이하인 점수" , ge90and90)


#2개 이상의 조건을 or 로 묶어줄 떄 쓸 수 있는 np.logical_or 함수
ge90or90 = mypoint[np.logical_or(mypoint<80,mypoint>90)]
print("80점보다 적거나 90점을 넘은점수" , ge90or90)



80점이 넘는 원소들의 모음 [82 91 88]
80점 이상이면서 90점 이하인 점수 [82 88]
80점보다 적거나 90점을 넘은점수 [77 91]


### Numpy 조건 연산
sql 의 if() 함수와 동일한 결과를 만들고, 파생 변수를 만들 때 유용한 npl.where 함수

In [44]:
exam = np.array([60,83,75,92,86])

#np.where 의 첫 파라미터로 주어진 조건이 참이면 합격, 아니면 불합격
result = np.where (exam>=80,"합격","불합격")
result

array(['불합격', '합격', '불합격', '합격', '합격'], dtype='<U3')

### 여러 조건 한번에 처리하기

In [ ]:
exam = np.array ([60,85,51,79,94,88])


#학점을 부여하기 위한 점수의 구건을 설정하는 조건들을 리스트로 설정
conditions = [ (exam >= 90),
               (exam >= 80),
               (exam >=70)
]

#조건에 따라 부여될 학점
value = ["A","B","C"]


result = np.select(conditions,value,default='F') #기본 값을 F 로 설정
result

array(['F', 'B', 'F', 'C', 'A', 'B'], dtype='<U1')