# LAB 01 - NumPy Library 1

## 03 그 밖의 ndarray 형태

### 라이브러리 참조하기

In [2]:
import numpy as np

## 2차원 배열
2차원 리스트를 ndarray 로 변환한다. ( 배열의 정보를 확인할 수 있는 프로퍼티가 포함된다)

- 차원의 크기 : ndim
- 차원별 원소수 : shape
- 원소의 데이터 타입 : dtype

In [5]:
myarray = np.array([
  [98,72,80,64],
  [88,90,80,72],
  [92,88,92,76]

])


print(myarray)

print("차원 크기:", myarray.ndim)
print("차원별 원소수:", myarray.shape)
print("원소의 데이터 타입:", myarray.dtype)

[[98 72 80 64]
 [88 90 80 72]
 [92 88 92 76]]
차원 크기: 2
차원별 원소수: (3, 4)
원소의 데이터 타입: int64


### boolean 타입으로 인덱싱
조건에 맞는 원소를 1차원 배열로 반환한다


In [7]:
# 1) Boolean 인덱싱: 조건에 맞는 항목만 1차원으로 추출
bool_array = np.array([
    [True,  False, True,  False],
    [True,  True,  True,  False],
    [True,  True,  True,  False]
])


#True 에 해당하는 원소만 출력되고, 조회한 형태는 2차원 데이터더라도 결과는 1차원으로 추출된다
result1 = myarray[bool_array]
print("result1:", result1)


result1: [98 80 88 90 80 92 88 92]


### 비교식에 의한 검색
조건에 맞는 원소를 1차우너 배열로 반환하고, 여기서도 and 와 or 조건을 활용할 수 있다

In [13]:
result2 = myarray[myarray >=80]
print("점수가 80점 이상인 원소들이 1차원 배열로 출력됩니다 : ",result2)


#and 조건은 logical_and()
result3=myarray[np.logical_and(myarray>=80,myarray <=90)]
print("점수가 80점 이상 이면서 90점 이하인 경우는 다음과 같습니다:",result3)


#or 조건은 logical_or()
result4=myarray[np.logical_or(myarray <80,myarray >90)]
print("점수가 80점 미만이거나 90점을 초과한 경우는 다음과 같습니다",result4)

점수가 80점 이상인 원소들이 1차원 배열로 출력됩니다 :  [98 80 88 90 80 92 88 92]
점수가 80점 이상 이면서 90점 이하인 경우는 다음과 같습니다: [80 88 90 80 88]
점수가 80점 미만이거나 90점을 초과한 경우는 다음과 같습니다 [98 72 64 72 92 92 76]


### 정형화된 특수한 형태의 배열 생성하기

In [17]:
#모든 원소가 0인 배열
np.zeros([3,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [19]:
#모든 원소가 1인 배열
np.ones([3,4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [21]:
#모든 원소가 특정 값인 배열
np.full([3,4],10)

array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10]])

In [23]:
#단위 행렬 (대각선 원소가 모두 1이고 그 외는 모두 0인 배열)
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### 랜덤 배열
0부터 1 범위에서 균등하게 추출하여 N 차원 랜덤 배열 생성

In [24]:
#10개의 값을 갖는 1차원 배열
np.random.rand(10)

array([0.89737407, 0.59180974, 0.49332354, 0.22749826, 0.81688653,
       0.2781697 , 0.14301452, 0.92662254, 0.6858114 , 0.25121888])

In [26]:
# 4행 3열인 2차원 랜덤 배열 생성 (첫 파라미터는 행, 두번쨰 파라미터는 열)
np.random.rand(4,3)

array([[0.76439056, 0.37069582, 0.88070871],
       [0.27131781, 0.31420086, 0.7956403 ],
       [0.58722712, 0.75011903, 0.86622938],
       [0.06840693, 0.53160604, 0.94480118]])

### 주어진 범위 안에서 정수값을 갖는 랜덤 배열
특정 범위를 지정해줄 수도 있다

In [28]:
# 0-9 사이의 랜덤값 10개의 원소를 갖는 1차원 배열
np.random.randint(0,9,10)

array([0, 5, 2, 0, 4, 7, 3, 0, 8, 4], dtype=int32)

In [30]:
#0-9 사이틔 랜덤값을 갖는 3행 4열의 2차 배열
np.random.randint(0,9,(3,4))

array([[3, 0, 4, 5],
       [3, 4, 6, 5],
       [4, 6, 2, 5]], dtype=int32)

### 랜던 시드 고정

In [32]:
np.random.seed(1234)
np.random.normal(0,1,(4,3))

array([[ 0.47143516, -1.19097569,  1.43270697],
       [-0.3126519 , -0.72058873,  0.88716294],
       [ 0.85958841, -0.6365235 ,  0.01569637],
       [-2.24268495,  1.15003572,  0.99194602]])

### 표준 정규 분포를 따르는 랜덤 배열
rand 뒤에 n 이 붙어있는 메서드를 사용하면 표준 정규 분포를 따르는 형태로 숫자가 랜덤 부여된다

In [34]:
np.random.randn(10)

array([ 0.19342138,  0.55343891,  1.31815155, -0.46930528,  0.67555409,
       -1.81702723, -0.18310854,  1.05896919, -0.39784023,  0.33743765])

In [35]:
np.random.randn(4,3)

array([[ 1.04757857,  1.04593826,  0.86371729],
       [-0.12209157,  0.12471295, -0.32279481],
       [ 0.84167471,  2.39096052,  0.07619959],
       [-0.56644593,  0.03614194, -2.0749776 ]])