# LAB 01 - NumPy Library 1

## 04 ndarray 형태 변환
1) 형변환 (type 변환)
 - 원소들의 데이터 타입 변경
   (1) astype() (2) asarray
   
2) 차원 변환
-차원 변경


### 라이브러리 참조하기

In [60]:
import numpy as np

### 원소의 데이터 타입 변환 (1) astype()

In [61]:
#0-10 전까지 1씩 증가하는 원소를 갖는 int 데이터 타입의 배열 생성
arr1=np.arange(10)
print("원본 배열 :" ,arr1)
print("원본 배열의 데이터타입",arr1.dtype)

원본 배열 : [0 1 2 3 4 5 6 7 8 9]
원본 배열의 데이터타입 int64


In [62]:
#실수 타입으로 변환

arr2=arr1.astype('float')
print("1차 형변환 후의 배열" , arr2)
print("1차 형변환 후의 배열의 데이터타입",arr2.dtype)

1차 형변환 후의 배열 [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
1차 형변환 후의 배열의 데이터타입 float64


In [63]:
#문자형 타입으로 변환

arr3=arr1.astype('str')
print("2차 형변환 후의 배열" , arr3)
print("2차 형변환 후의 배열의 데이터타입",arr3.dtype)

2차 형변환 후의 배열 ['0' '1' '2' '3' '4' '5' '6' '7' '8' '9']
2차 형변환 후의 배열의 데이터타입 <U21


### 원소의 데이터 타입 변환 (2) asarray()

In [64]:
#10-20 전까지 1씩 증가하는 원소를 갖는 int 데이터 타입의 배열 생성
arr1=np.arange(10,20)
print("원본 배열 :" ,arr1)
print("원본 배열의 데이터타입",arr1.dtype)

원본 배열 : [10 11 12 13 14 15 16 17 18 19]
원본 배열의 데이터타입 int64


In [65]:
#실수 타입으로 변환

arr2=np.asarray (arr1,dtype='float')
print("1차 형변환 후의 배열" , arr2)
print("1차 형변환 후의 배열의 데이터타입",arr2.dtype) 


1차 형변환 후의 배열 [10. 11. 12. 13. 14. 15. 16. 17. 18. 19.]
1차 형변환 후의 배열의 데이터타입 float64


In [66]:
#문자형 타입으로 변환

arr3=np.asarray(arr1,dtype='str')
print("2차 형변환 후의 배열" , arr3)
print("2차 형변환 후의 배열의 데이터타입",arr3.dtype)

2차 형변환 후의 배열 ['10' '11' '12' '13' '14' '15' '16' '17' '18' '19']
2차 형변환 후의 배열의 데이터타입 <U21


### 차원 변환 - reshape 함수

In [67]:
# 1-20 전 까지 1씩 증가하는 값을 갖는 1차원 배열 생성
origin = np.arange(20)
origin

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [68]:
#1차원 배열을 4x5 2차원 배열로 변환 (reshape 메서드 설정값은 원소의 총 갯수와 일치해야한다)
x=origin.reshape(4,5)
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

### 차원 축소 - reshape 함수를 활용

In [69]:
myorigin = np.array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])


myorigin

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [70]:
# 단순 reshape 함수 사용을 통한 1차원 배열로 차원 축소하기 
#reshape 함수에 파라미터를 1개만 넣으면 열을 의미하고, 결국 20개의 원소를 갖는 1차 배열로 재구성 된다


y=myorigin.reshape(20)
y

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [71]:
#원소의 수를 계산하여 1차원 배열로 축소하기
#shape 메서드로 행과 열의 갯수를 구해 해당 값을 활용한다
rows,cols = myorigin.shape
rows,cols

(4, 5)

In [72]:
z=origin.reshape(rows*cols)
z

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

### reshape 에서 -1 의 의미
- n 개 라는 의미로 이해하자 : reshape 함수 안에서 -1 이 파라미터로 쓰이면, 설정된 파라미터 외 남은 차원에 대해 추정된다는 뜻 
- 예를 들어서 10개의 원소에 열이 2라고 써져있으면, 행은 자연스럽게 5로 설정된다

In [73]:
reshaping = np.array([[0,1,2,3],
                      [4,5,6,7],
                      [8,9,10,11]])
reshaping

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [74]:
#행의 위치가 -1 인 경우 
#행의 수에 관계 없이 1열을 갖는 2차원 배열
x=reshaping.reshape(-1,1)
x

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11]])

In [75]:
# 행의 수에 관계없이 2열을 갖는 2차원 배열
y=reshaping.reshape(-1,2)
y

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [76]:
# 열의 위치가 -1 인 경우
origin = np.arange(12)
origin

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [77]:
#열의 수에 관계없이 1행을 갖는 2차원 배열로 재구성
x= origin.reshape(1,-1)
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]])

In [78]:
#열의 수에 관계 없이 2행을 갖는 2차원 배열로 재구성
y= origin.reshape(2,-1)
y

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [79]:
#reshape(-1) 인경우, 행의 수에 관계 없이  n 개의 열로 재구성 되면서 1차원 배열로 변환된다


origin =np.array([[0,1,2,3,4,5,6,7,8,9,10,11]])

print(origin)


#1차원 배열로 재배치
x=origin.reshape(-1)
x

[[ 0  1  2  3  4  5  6  7  8  9 10 11]]


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

## 테스트

In [80]:
# 열의 위치가 -1 인 경우
test1= np.arange(12)
test1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [81]:
a=test1.reshape(1,-1)
b=test1.reshape(-1,1)

print("열의 자리가 -1 이므로, 열의 수에 상관없이 1행을 갖는 2차원 배열로 재구성",a)

print("행의 자리가 -1 이므로, 행의 수에 상관없이 1행을 갖는 2차원 배열로 재구성 :",b)

열의 자리가 -1 이므로, 열의 수에 상관없이 1행을 갖는 2차원 배열로 재구성 [[ 0  1  2  3  4  5  6  7  8  9 10 11]]
행의 자리가 -1 이므로, 행의 수에 상관없이 1행을 갖는 2차원 배열로 재구성 : [[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]]


In [82]:
test2 = np.array([[0,1,2,3],
                      [4,5,6,7],
                      [8,9,10,11]])
test2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [83]:
c=test2.reshape(1,-1)
d=test2.reshape(-1,1)

print(c)

print(d)

[[ 0  1  2  3  4  5  6  7  8  9 10 11]]
[[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]]
