# LAB 01 - NumPy Library 1

## 01 Numpy 시작하기 연습문제

다음 조건을 모두 만족하는 파이썬 코드를 작성하시오.
<출력예시>
- NumPy의 ndarray를 활용하여
 1. 정수 10,20,30,40,50 으로 구성된 배열을 생성하고,
 2. 배열의 길이(원소 개수)를 출력하며,
 3. 배열의 첫번째 원소와 마지막 두 개 원소를 각각 출력하고,
 4. for문과 enumerate()를 이용해 인덱스와 값을 함께 출력하시오.


In [2]:
import numpy as np

In [50]:


# 1. 정수 10,20,30,40,50 으로 구성된 배열을 생성하고,
myarr = np.array([10,20,30,40,50])

 # 2. 배열의 길이(원소 개수)를 출력하며,
print("myarr 배열의 길이는:",len(myarr))

 
 # 3. 배열의 첫번째 원소와 마지막 두 개 원소를 각각 출력하고,
print("배열의 첫 번째 원소는" , myarr[0])
print("배열의 마지막 두 개 원소는" , myarr[3:5])
print("배열의 마지막 두 개 원소는" , myarr[-2:])

 # 4. for문과 enumerate()를 이용해 인덱스와 값을 함께 출력하시오.
for i,v in enumerate(myarr):
  print("%d 번째 원소는 %d" %(i,v))


  print(f"f 스트링 방식 : {i} 번째 원소 >> {v}")


myarr 배열의 길이는: 5
배열의 첫 번째 원소는 10
배열의 마지막 두 개 원소는 [40 50]
배열의 마지막 두 개 원소는 [40 50]
0 번째 원소는 10
f 스트링 방식 : 0 번째 원소 >> 10
1 번째 원소는 20
f 스트링 방식 : 1 번째 원소 >> 20
2 번째 원소는 30
f 스트링 방식 : 2 번째 원소 >> 30
3 번째 원소는 40
f 스트링 방식 : 3 번째 원소 >> 40
4 번째 원소는 50
f 스트링 방식 : 4 번째 원소 >> 50


## 02 ndarray 의 주요 기능
당신은 한 학급의 성적데이터를 NumPy로 분석해야하는 데이터분석가 입니다.
- 학생 6 명의 점수 데이터가 다음과 같이 주어집니다

score =  [72.5, 88.0, 91.5, 67.0, 80.0, 59.5]


 ☐ 다음조건에따라코드를작성하세요.
 - 위 점수 리스트를 정수형 ndarray로 변환하시오.
 - 점수가 80점 이상인 학생의 점수만 추출하여 출력하시오.
 - 모든 학생에게 다음기준으로 학점을 부여하고 결과를 출력하시오
(90점이상→‘A’ | 80점이상→‘B’ | 70점이상→‘C’ | 그외→‘F)


In [46]:

# 1. dtype 파라미터로 데이터 타입을 강제로 지정해줄 수 있고, int 로 지정하면 소수점은 모두 사라진다

score = np.array ([72.5, 88.0, 91.5, 67.0, 80.0, 59.5],dtype=int)

print("원본 점수는",score)   

# 2. 점수가 80점 이상인 경우만 추출하기 위해 ndarray 뒤에 조건을 걸어준다
more80score = score[score>=80]
print("80점 이상 점수는",more80score)


# 3. 모든 학생에게 특정 기준으로 학점을 부여하고 결과를 추출하시오

score_conditions =[ (score >=90),
                    (score >=80),
                    (score >=70)
]


score_value = ['A','B','C']

result=np.select(score_conditions,score_value,default='F')
print("각 점수에 대한 등급은" , result)

원본 점수는 [72 88 91 67 80 59]
80점 이상 점수는 [88 91 80]
각 점수에 대한 등급은 ['C' 'B' 'A' 'F' 'B' 'F']


## 03 그 밖의 ndarray 형태


당신은 AI 교육기관에서 수강생들의 모의 시험 데이터를 검수하는 일을 맡고있습니다.시험 데이터는 3회차 시험 ×4명 학생의 점수로 구성되어야 합니다. 다음 조건에 맞게
NumPy로 코드를 작성하세요.
 
 <출력예시>
 AI 교육생점수 데이터 점검하기
1. 평균이 75, 표준편차가 5인 정규분포를 따르는 랜덤 점수 데이터를 3행 4열 배열로 생성하시오. (단, 결과가 재현되도록 랜덤 시드를 100으로 고정해야 함. )
2. 생성된 점수 중 80점 이상인 항목만 추출하시오.
3. 점수가 저장된 배열의 차원(ndim), 형태(shape), 데이터 타입(dtype) 을 각각 출력하시오

In [47]:
np.random.seed(100)
array3=np.random.normal(75,5,(3,4))
print("배열 데이터 확인" , array3)


more_80=array3[array3>=80]
print("80점이 넘는 경우는", more_80)

array3_ndim=array3.ndim
array3_shape=array3.shape
array3_dtype=array3.dtype

print("차원 : ",array3_ndim)
print("형태 : ",array3_shape)
print("데이터 타입 : ",array3_dtype)

배열 데이터 확인 [[66.25117263 76.71340202 80.76517901 73.73781982]
 [79.90660393 77.57109421 76.10589835 69.64978335]
 [74.05252085 76.27500722 72.70986507 77.17581744]]
80점이 넘는 경우는 [80.76517901]
차원 :  2
형태 :  (3, 4)
데이터 타입 :  float64


## 04 ndarray 형태 변환
당신은 데이터 분석팀의 “전처리 담당자” 입니다.
팀에서 전달받은 데이터는 형태도 제각각이고, 타입도 일관되지 않아 분석이 어렵습니다.아래 조건에 따라 NumPy를 이용해 데이터 타입과 구조를 정리하세요.
데이터 포맷 정리
1. 0부터 11까지의 정수를 가지는 배열을 생성하시오.
2. 이 배열을 실수형(float) 으로 변환하시오.
3. 변환된 배열을 2행 6열 구조로 재배치하시오.
4. 이후, 열의 수에 관계없이 3행으로 자동 변환되도록 𝑟𝑒𝑠ℎ𝑎𝑝𝑒()함수를 이용하시오.
5. 마지막으로, 1차원 배열로 축소하여 결과를 출력하시오.


In [48]:
#0부터 11까지의 정수를 가지는 배열
mytest = np.arange(0,12)
print("원본 배열:", mytest)

#실수형으로 형변환
mytest_float = mytest.astype(float)
print("실수형 변환:", mytest_float)

#2행 6열 구조로 재배치
mytest_26 = mytest.reshape(2,6)
print("2행 6열 형태:", mytest_26)

# 3행으로 자동 변환
mytest_3row= mytest.reshape(3,-1)
print("자동 계산된 형태:", mytest_3row)


#1차원으로 배열 축소
mytest_1d =mytest.reshape(-1)
print("1차원 배열로 축소:", mytest_1d)


원본 배열: [ 0  1  2  3  4  5  6  7  8  9 10 11]
실수형 변환: [ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]
2행 6열 형태: [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
자동 계산된 형태: [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
1차원 배열로 축소: [ 0  1  2  3  4  5  6  7  8  9 10 11]


## 05 기초 통계량의 이해 1
당신은 게임 회사 데이터 분석가 입니다.두 팀,'Alpha'와'Bravo'의 게임 점수
데이터가 주어졌습니다.각 팀의 점수에 대한 기초통계량을 아래표와 같이 산출하세요.

In [13]:

alpha=np.array([88,92,76,100,95,81,79,98,85,87])
bravo=np.array([65,99,78,72,80,91,75,82,89,70])


print("alpha의 도수 : ", len(alpha) , "| bravo 의 도수: " , len(bravo))
print("alpha의 평균 : ", np.average(alpha) , "| bravo 의 평균: " , np.average(bravo))
print("alpha의 표준편차 : ", np.std(alpha,ddof=1) , "| bravo 의 표준편차: " , np.std(bravo,ddof=1))
print("alpha의 최소값 : ", np.min(alpha) , "| bravo 의 최소값: " , np.min(bravo))
print("alpha의 1사분위 수 : ", np.quantile(alpha,0.25) , "| bravo 의 1사분위수: " , np.quantile(bravo,0.25))
print("alpha의 중위값 : ", np.median(alpha) , "| bravo 의 중위값: " , np.median(bravo))
print("alpha의 3사분위 수 : ", np.quantile(alpha,0.75) , "| bravo 의 3사분위수: " , np.quantile(bravo,0.75))
print("alpha의 최대값 : ", np.max(alpha) , "| bravo 의 최대값: " , np.max(bravo))


alpha의 도수 :  10 | bravo 의 도수:  10
alpha의 평균 :  88.1 | bravo 의 평균:  80.1
alpha의 표준편차 :  8.116512661098842 | bravo 의 표준편차:  10.461038826681284
alpha의 최소값 :  76 | bravo 의 최소값:  65
alpha의 1사분위 수 :  82.0 | bravo 의 1사분위수:  72.75
alpha의 중위값 :  87.5 | bravo 의 중위값:  79.0
alpha의 3사분위 수 :  94.25 | bravo 의 3사분위수:  87.25
alpha의 최대값 :  100 | bravo 의 최대값:  99


## 06 기초 통계량의 이해 2-1
당신은 한 온라인 상점의 한달 간 일일 판매량 데이터를 분석하는 임무를 맡았습니다.
주어진 데이터를 사용하여 판매량 분포를 파악하고, 아래 요구 사항에 따라 분석결과를
출력하는 Python 코드를 작성하세요



 1. 주어진 일일 판매량 데이터를 `numpy` 배열로 생성하세요.
 2. 판매량 구간을 `[0, 10, 20, 30, 40, 50]` 으로 직접 설정하여 도수분포를 분석하세요. 
 3. 2번의 도수 분포표를 활용하여 절대도수, 상대도수, 누적도수를 포함하는 도수분포표를 
출력하세요.
 •상대도수는 소수점 넷째 자리에서 반올림하여 셋째 자리까지 표시하세요.

In [15]:
import numpy as np

daily_sales_data = np.array([18,25,33,21,28,40,15,3,9,17,22,29,38,45,11,6,31,24,27,35,12,19,39,42,7,2,20,34,26,30])



hist,bins = np.histogram(daily_sales_data,[0,10,20,30,40,50])
print("구간별 데이터 수:" , hist) #절대도수
print("구간 경계",bins)

구간별 데이터 수: [5 6 9 7 3]
구간 경계 [ 0 10 20 30 40 50]


In [23]:
#상대도수
relative_freq = hist/ np.sum(hist)
np.round(relative_freq,3)

array([0.167, 0.2  , 0.3  , 0.233, 0.1  ])

In [24]:
#누적 도수
cum_freq = []
previous = 0

for i in hist:
  previous +=i
  cum_freq.append(previous)
previous

np.int64(30)

## 06 기초 통계량의 이해 2-2
다음의 데이터는 2024년도 월별 교통사고 건수이다.
이 데이터에 대해 기초통계량을 구하고 이를 통해 알 수 있는 사실을 하나 이상
서술하시오.

In [ ]:
import numpy as np

accident = np.array ([15129,13836,15738,16300,17605,16690,16252,17000,16956,17720,17455,15668])


print("월평균 교통사고 건수 : ", np.round(np.average(accident),0))


# 사분위수 구간 (IQR)
print("사분위수 구간(IQR):", np.quantile(accident,0.75)-np.quantile(accident,0.25))


#분산 표준편차
print("분산", np.round(np.var(accident),1))
print("표준편차",np.round(np.std(accident),1))


#중앙값
print("중앙값",np.median(accident))


#최대값과 최소값
print("최대값",np.max(accident))
print("최소값",np.min(accident))


월평균 교통사고 건수 :  16362.0
사분위수 구간(IQR): 1393.25
분산 1186603.7
표준편차 1089.3
중앙값 16495.0
최대값 17720
최소값 13836


In [ ]:
#Q1. 분기별로 교통사고 총 수에 차이가 있을까? 어떤 분기에서 사고가 가장 많이 발생했을까?
#>  1분기의 사고 발생수가 가장 적고, 2-4 분기는 대체적으로 비슷한 수준이나 4분기에 사고 발생수가 가장 높았음
months_3=accident.reshape(4,3)
sum1 = np.sum(months_3,axis=1)
print(sum1)




[44703 50595 50208 50843]


In [ ]:
#Q2. 2024년 공휴일수가 영향을 준게 있었을까?
#> 공휴일수만으로는 관련성 확인이 어려웠지만, 공휴일이 가장 많은 2월에 사고 발생수가 가장 적었다. 만약 추가 데이터를 확인한다면 대중교통으로 이동 수단이 분산되었거나, 긴 연휴 시기에 해외 여행 수요가 높아졌는지 확인해봐도 좋을 것 같다.

holiday = np.array([1,4,1,1,3,1,0,1,3,2,0,1])   #네이버 달력

In [ ]:
#Q3. 2월은 다른 달 보다 일수가 적은데, 일 평균으로 보면 월별로 사고 건수에 차이가 있었을까?
#> 일 평균으로 보아도 2월의 사고 발생수가 가장 적었고, 가장 높았던건 11월
month_day_number = np.array([31,29,31,30,31,30,31,31,30,31,30,31])

np.round(accident/month_day_number,0)


array([488., 477., 508., 543., 568., 556., 524., 548., 565., 572., 582.,
       505.])