# LAB 01 - NumPy Library 1

## 01 Numpy 시작하기 연습문제

다음 조건을 모두 만족하는 파이썬 코드를 작성하시오.
<출력예시>
- NumPy의 ndarray를 활용하여
 1. 정수 10,20,30,40,50 으로 구성된 배열을 생성하고,
 2. 배열의 길이(원소 개수)를 출력하며,
 3. 배열의 첫번째 원소와 마지막 두 개 원소를 각각 출력하고,
 4. for문과 enumerate()를 이용해 인덱스와 값을 함께 출력하시오.


In [44]:
import numpy as np

In [50]:


# 1. 정수 10,20,30,40,50 으로 구성된 배열을 생성하고,
myarr = np.array([10,20,30,40,50])

 # 2. 배열의 길이(원소 개수)를 출력하며,
print("myarr 배열의 길이는:",len(myarr))

 
 # 3. 배열의 첫번째 원소와 마지막 두 개 원소를 각각 출력하고,
print("배열의 첫 번째 원소는" , myarr[0])
print("배열의 마지막 두 개 원소는" , myarr[3:5])
print("배열의 마지막 두 개 원소는" , myarr[-2:])

 # 4. for문과 enumerate()를 이용해 인덱스와 값을 함께 출력하시오.
for i,v in enumerate(myarr):
  print("%d 번째 원소는 %d" %(i,v))


  print(f"f 스트링 방식 : {i} 번째 원소 >> {v}")


myarr 배열의 길이는: 5
배열의 첫 번째 원소는 10
배열의 마지막 두 개 원소는 [40 50]
배열의 마지막 두 개 원소는 [40 50]
0 번째 원소는 10
f 스트링 방식 : 0 번째 원소 >> 10
1 번째 원소는 20
f 스트링 방식 : 1 번째 원소 >> 20
2 번째 원소는 30
f 스트링 방식 : 2 번째 원소 >> 30
3 번째 원소는 40
f 스트링 방식 : 3 번째 원소 >> 40
4 번째 원소는 50
f 스트링 방식 : 4 번째 원소 >> 50


## 02 ndarray 의 주요 기능
당신은 한 학급의 성적데이터를 NumPy로 분석해야하는 데이터분석가 입니다.
- 학생 6 명의 점수 데이터가 다음과 같이 주어집니다

score =  [72.5, 88.0, 91.5, 67.0, 80.0, 59.5]


 ☐ 다음조건에따라코드를작성하세요.
 - 위 점수 리스트를 정수형 ndarray로 변환하시오.
 - 점수가 80점 이상인 학생의 점수만 추출하여 출력하시오.
 - 모든 학생에게 다음기준으로 학점을 부여하고 결과를 출력하시오
(90점이상→‘A’ | 80점이상→‘B’ | 70점이상→‘C’ | 그외→‘F)


In [46]:

# 1. dtype 파라미터로 데이터 타입을 강제로 지정해줄 수 있고, int 로 지정하면 소수점은 모두 사라진다

score = np.array ([72.5, 88.0, 91.5, 67.0, 80.0, 59.5],dtype=int)

print("원본 점수는",score)   

# 2. 점수가 80점 이상인 경우만 추출하기 위해 ndarray 뒤에 조건을 걸어준다
more80score = score[score>=80]
print("80점 이상 점수는",more80score)


# 3. 모든 학생에게 특정 기준으로 학점을 부여하고 결과를 추출하시오

score_conditions =[ (score >=90),
                    (score >=80),
                    (score >=70)
]


score_value = ['A','B','C']

result=np.select(score_conditions,score_value,default='F')
print("각 점수에 대한 등급은" , result)

원본 점수는 [72 88 91 67 80 59]
80점 이상 점수는 [88 91 80]
각 점수에 대한 등급은 ['C' 'B' 'A' 'F' 'B' 'F']


## 03 그 밖의 ndarray 형태


당신은 AI 교육기관에서 수강생들의 모의 시험 데이터를 검수하는 일을 맡고있습니다.시험 데이터는 3회차 시험 ×4명 학생의 점수로 구성되어야 합니다. 다음 조건에 맞게
NumPy로 코드를 작성하세요.
 
 <출력예시>
 AI 교육생점수 데이터 점검하기
1. 평균이 75, 표준편차가 5인 정규분포를 따르는 랜덤 점수 데이터를 3행 4열 배열로 생성하시오. (단, 결과가 재현되도록 랜덤 시드를 100으로 고정해야 함. )
2. 생성된 점수 중 80점 이상인 항목만 추출하시오.
3. 점수가 저장된 배열의 차원(ndim), 형태(shape), 데이터 타입(dtype) 을 각각 출력하시오

In [47]:
np.random.seed(100)
array3=np.random.normal(75,5,(3,4))
print("배열 데이터 확인" , array3)


more_80=array3[array3>=80]
print("80점이 넘는 경우는", more_80)

array3_ndim=array3.ndim
array3_shape=array3.shape
array3_dtype=array3.dtype

print("차원 : ",array3_ndim)
print("형태 : ",array3_shape)
print("데이터 타입 : ",array3_dtype)

배열 데이터 확인 [[66.25117263 76.71340202 80.76517901 73.73781982]
 [79.90660393 77.57109421 76.10589835 69.64978335]
 [74.05252085 76.27500722 72.70986507 77.17581744]]
80점이 넘는 경우는 [80.76517901]
차원 :  2
형태 :  (3, 4)
데이터 타입 :  float64


## 04 ndarray 형태 변환
당신은 데이터 분석팀의 “전처리 담당자” 입니다.
팀에서 전달받은 데이터는 형태도 제각각이고, 타입도 일관되지 않아 분석이 어렵습니다.아래 조건에 따라 NumPy를 이용해 데이터 타입과 구조를 정리하세요.
데이터 포맷 정리
1. 0부터 11까지의 정수를 가지는 배열을 생성하시오.
2. 이 배열을 실수형(float) 으로 변환하시오.
3. 변환된 배열을 2행 6열 구조로 재배치하시오.
4. 이후, 열의 수에 관계없이 3행으로 자동 변환되도록 𝑟𝑒𝑠ℎ𝑎𝑝𝑒()함수를 이용하시오.
5. 마지막으로, 1차원 배열로 축소하여 결과를 출력하시오.


In [48]:
#0부터 11까지의 정수를 가지는 배열
mytest = np.arange(0,12)
print("원본 배열:", mytest)

#실수형으로 형변환
mytest_float = mytest.astype(float)
print("실수형 변환:", mytest_float)

#2행 6열 구조로 재배치
mytest_26 = mytest.reshape(2,6)
print("2행 6열 형태:", mytest_26)

# 3행으로 자동 변환
mytest_3row= mytest.reshape(3,-1)
print("자동 계산된 형태:", mytest_3row)


#1차원으로 배열 축소
mytest_1d =mytest.reshape(-1)
print("1차원 배열로 축소:", mytest_1d)


원본 배열: [ 0  1  2  3  4  5  6  7  8  9 10 11]
실수형 변환: [ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]
2행 6열 형태: [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
자동 계산된 형태: [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
1차원 배열로 축소: [ 0  1  2  3  4  5  6  7  8  9 10 11]
